### ISSUE TITLE
No "From" indicated for Coins/Hours transferred from a wallet

### ISSUE THREAD

**Issue by fray** [skycoin/coinhour-bank-issues#11]
**Issue:**
No indication of where a deposit originated when sent from a wallet instead of an email address.

**Expected Results:**
I thought we might at least see the Tx ID or wallet address in the "From" field on transfers to the Coinhour Bank from a Skycoin wallet address.

**Actual Results:**
The "From" field is left blank.

**Steps to reproduce:**
1. Send Skycoin and Coin Hours from a wallet address to the Coinhour Bank.
2. Look at the transaction history panel on the Coinhour bank account page.

![Screen Shot 2019-04-23 at 5 08 05 PM](https://user-images.githubusercontent.com/1222906/56621798-2b519e80-65eb-11e9-9031-c9060660f4e5.png)

**Comment by fray** [comment]
In a recent update this was changed so that Tx IDs are listed, but the "from" only displays the current account email, rather than the wallet address that originated the deposit, which seems more appropriate.

**Comment by Chris-PS** [comment]
Since this is in a new ticket, closing this one.
