### ISSUE TITLE
sending ch to a new accounts email problem

### ISSUE THREAD

**Issue by GoldCoinHours** [skycoin/coinhour-bank-issues#12]
Issue:
error shown to sender when receiver has not opened their address yet

expected results: 
sending and receiving go smoothly 

actual results:
failure to send ch

steps to reproduce
1 open "new" account
2 open existing account
3 send ch to "new" account
4 error shown cant send ch
5 go to new account and view address
6 go to existing account and try to send ch to new account again
7 this time sending works because new address has been viewed (created?)

**Comment by Chris-PS** [comment]
It is expected that a new user logs in to the CH Bank at least once before receiving funds. Right now there are no plans to change that, but we will keep it in mind for later stages.
