### ISSUE TITLE
Transaction History cannot be sorted or truncated

### ISSUE THREAD

**Issue by fray** [skycoin/coinhour-bank-issues#14]
**Title/Summary:**
The panel listing all transactions on the main account page does not appear to paginate after a certain number of transactions. For accounts with many transactions, this makes for a very long page. (I have 134 transactions right now, and they are all visible if I scroll down.)

**Expected results:**
There would be some mechanism to only show the _X_ most recent transactions, or some kind of filtering mechanism, where one could "see more" if they needed to.

**Actual results:**
The page becomes incredibly long quite quickly as transactions build up and never clear.

**Steps to reproduce:**
Generate dozens or hundreds of transactions, and they are all visible on the page.

![Screen Shot 2019-04-23 at 10 43 49 PM](https://user-images.githubusercontent.com/1222906/56633137-2f48e500-661a-11e9-9ecc-d0d3b3b9051b.png)
![Screen Shot 2019-04-23 at 10 44 10 PM](https://user-images.githubusercontent.com/1222906/56633142-32dc6c00-661a-11e9-9d8a-f99db5b349ed.png)

**Comment by Zordon77** [comment]
Might consider grouping transaction history by email address/user too

**Comment by Chris-PS** [comment]
This will be resolved with the Transaction History Sequence ticket.
