### ISSUE TITLE
Transaction History Sequence

### ISSUE THREAD

**Issue by caariiboouu** [skycoin/coinhour-bank-issues#16]
![2019-04-24_01-53](https://user-images.githubusercontent.com/7329254/56638529-0afa0200-6634-11e9-8cc1-0b25789eaeea.png)

Expected: Transactions ordered by date.
Actual: Seemingly randomly sorted transactions.
Reproduce: Create ~10 transactions.

**Comment by fizzle24** [comment]
and change to ascending date order for more recent transactions first
