### ISSUE TITLE
Copy deposit address doesnt work on iPhone on any browser

### ISSUE THREAD

**Issue by asxtree** [skycoin/coinhour-bank-issues#26]
**SUMMARY:**

The copy button of the Deposit address does not work on iPhone browsers ( mozilla, chrome or safari )

**Expected results:**
When the copy button is pressed the address should be copied to clipboard

**Actual results:**
The address is not copied in clipboard

**Steps to reproduce:**

1. Open safari on iPhone and go on the CHB
2. After you login select the Deposit button
3. Press the copy button
![Untitled](https://user-images.githubusercontent.com/34941232/57567840-f9f91100-73e7-11e9-996c-9ed7424f7995.png)

4. Open Notes on iPhone and paste 
5. Observe that the address was not copied

**Comment by Chris-PS** [comment]
Not working on iphone yet.
