### ISSUE TITLE
Confirmation Email not passing along withdraw values.

### ISSUE THREAD

**Issue by caariiboouu** [skycoin/coinhour-bank-issues#33]
![Screen Shot 2019-06-25 at 1 00 18 PM](https://user-images.githubusercontent.com/7329254/60121797-87e74c00-9749-11e9-8bbd-98971e927a84.jpg)
![Screen Shot 2019-06-25 at 1 00 27 PM](https://user-images.githubusercontent.com/7329254/60121799-87e74c00-9749-11e9-8efc-a38649982a75.jpg)

**Comment by Zordon77** [comment]
withdrew today and got this: You requested withdrawal of 0.001 coin(s) and 197 hour(s) from the bank. and then this: You successfully withdrew 0.001 coin(s) and 98 hour(s) from the bank including fee. Not sure how that 98 was calculated.
