### ISSUE TITLE
Transfer CH window

### ISSUE THREAD

**Issue by JMoojie** [skycoin/coinhour-bank-issues#7]
**Title/Summary:**
Email Transfer window doesn't close once sent, allowing double sending
**Expected results:**
Once email, and amount are filled out, pressing the continue button should close the window. confirming the send has been complete.
**Actual results:**
The window stays open, and if continue is pressed again, it repeats the transfer
Steps to reproduce:

**Comment by Zordon77** [comment]
Might consider requiring some sort of authentication before CHs can be sent too
